---
name: Test

on:
  push:
    tags-ignore:
      - '**'
    paths:
      - '*.php'
      - 'composer.json'
  pull_request:
    paths:
      - '*.php'
      - 'composer.json'
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [ '7.2', '7.3', '7.4' ]
    name: PHP ${{ matrix.php-versions }} Test

    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: json
          coverage: none
          tools: cs2pr, phpstan, phpunit
        env:
          COMPOSER_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run PHPStan
        run: phpstan analyse --error-format=checkstyle src | cs2pr

      - name: Setup problem matchers for PHPUnit
        run: echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

      - name: Install dependencies
        run: composer install --prefer-dist --no-interaction --no-suggest

      - name: Execute tests
        run: vendor/bin/phpunit --verbose
